# 超时和延迟配置
import os
from dotenv import load_dotenv
load_dotenv()

# 响应超时
RESPONSE_COMPLETION_TIMEOUT = int(os.environ.get('RESPONSE_COMPLETION_TIMEOUT', '300000'))
INITIAL_WAIT_MS_BEFORE_POLLING = int(os.environ.get('INITIAL_WAIT_MS_BEFORE_POLLING', '500'))
POLLING_INTERVAL = int(os.environ.get('POLLING_INTERVAL', '300'))
POLLING_INTERVAL_STREAM = int(os.environ.get('POLLING_INTERVAL_STREAM', '180'))
SILENCE_TIMEOUT_MS = int(os.environ.get('SILENCE_TIMEOUT_MS', '60000'))
POST_SPINNER_CHECK_DELAY_MS = int(os.environ.get('POST_SPINNER_CHECK_DELAY_MS', '500'))
FINAL_STATE_CHECK_TIMEOUT_MS = int(os.environ.get('FINAL_STATE_CHECK_TIMEOUT_MS', '1500'))
POST_COMPLETION_BUFFER = int(os.environ.get('POST_COMPLETION_BUFFER', '700'))

# 界面交互超时
CLEAR_CHAT_VERIFY_TIMEOUT_MS = int(os.environ.get('CLEAR_CHAT_VERIFY_TIMEOUT_MS', '5000'))
CLEAR_CHAT_VERIFY_INTERVAL_MS = int(os.environ.get('CLEAR_CHAT_VERIFY_INTERVAL_MS', '2000'))
CLICK_TIMEOUT_MS = int(os.environ.get('CLICK_TIMEOUT_MS', '3000'))
CLIPBOARD_READ_TIMEOUT_MS = int(os.environ.get('CLIPBOARD_READ_TIMEOUT_MS', '3000'))
WAIT_FOR_ELEMENT_TIMEOUT_MS = int(os.environ.get('WAIT_FOR_ELEMENT_TIMEOUT_MS', '10000'))
PSEUDO_STREAM_DELAY = float(os.environ.get('PSEUDO_STREAM_DELAY', '0.01'))

# 睡眠间隔 (秒)
SLEEP_TICK = 0.1
SLEEP_SHORT = 0.15
SLEEP_MEDIUM = 0.25
SLEEP_LONG = 0.5
SLEEP_RETRY = 1.0
SLEEP_NAVIGATION = 2.0
SLEEP_VIDEO_POLL = 5.0
SLEEP_CLEANUP = 10.0
SLEEP_IMAGE_UPLOAD = 0.8

# 操作延迟 (秒)
DELAY_AFTER_CLICK = 0.15
DELAY_AFTER_FILL = 0.2
DELAY_AFTER_TOGGLE = 0.3
DELAY_BEFORE_SUBMIT = 0.1
DELAY_AFTER_ESCAPE = 0.1
DELAY_BETWEEN_RETRIES = 0.5

# Playwright超时 (毫秒)
TIMEOUT_ELEMENT_VISIBLE = 5000
TIMEOUT_ELEMENT_ENABLED = 10000
TIMEOUT_ELEMENT_ATTACHED = 15000
TIMEOUT_PAGE_NAVIGATION = 30000
TIMEOUT_WRAPPER_VISIBLE = 35000
TIMEOUT_RESPONSE_ATTACHED = 90000
TIMEOUT_DOWNLOAD = 15000
TIMEOUT_DOWNLOAD_VIDEO = 120000
TIMEOUT_INNER_TEXT = 1000
TIMEOUT_INPUT_VALUE = 2000
TIMEOUT_SELECTOR_MATCH = 3000
TIMEOUT_SUBMIT_ENABLED = 15000

# 重试和流式配置
MAX_RETRIES = 3
MAX_WAIT_UPLOAD_VERIFY = 10.0
MAX_EMPTY_RETRIES_STREAM = 300
BASE_STREAM_RETRIES = 300
STREAM_CHUNK_SIZE = 50

# 其他
RECOVERY_HOURS = 6.0
KEEPALIVE_TIMEOUT = 30
NEW_CHAT_URL = 'https://aistudio.google.com/prompts/new_chat'